services:
  fastapi:
    image: dwani/discovery-server:latest  # Replace with your FastAPI Docker image
    container_name: fastapi_server
    ports:
      - "8000:18888"  # Expose FastAPI server port (adjust if needed)
    environment:
      - DWANI_API_BASE_URL=https://
      - DWANI_API_KEY=  #add -key -here  
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to host's localhost
    restart: unless-stopped

networks:
  app-network:
    driver: bridge